version: '3.4'
services:
  powerbiportal.api:
    volumes:
      - 'c:/${ATTACH_DISK}/PowerBiPortal.Api/wwwroot:/usr/app/wwwroot/'
    environment:
      - 'ASPNETCORE_ENVIRONMENT=Sandbox'
      - 'ConnectionString=Server=mssql,1433;Database=powerbiportaldb;User Id=sa;Password=${DB_PASSWORD};MultipleActiveResultSets=true;'
    build: 
      context: ../../PowerBiPortal.Api/
      dockerfile: ./Dockerfile.original