version: "3.4"
services:
  svg2font.api:
    volumes:
      - "c:/${ATTACH_DISK}/app/svg2font/wwwroot:/usr/app/wwwroot/"
    environment:
      - "ASPNETCORE_ENVIRONMENT=Sandbox"
    build:
      context: ../../Svg2Font.Api/
      dockerfile: ./Dockerfile.original
  svg2font.generator:
    volumes:
      - "c:/${ATTACH_DISK}/app/svg2font/wwwroot/icon:/app/uploads/:ro"
    build:
      context: ../../Svg2Font.Generator/
