version: '3.4'
services:
  nginx:
    image: 'nginx:alpine'
    container_name: nginx
    command:
      - nginx
      - '-g'
      - daemon off;
    ports:
      - '80:80'
      - '443:443'
    restart: always
    volumes:
      - './nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './nginx/sites-enabled:/etc/nginx/sites-enabled/'
      - './nginx/static:/usr/share/nginx/'
  mssql:
    image: brickclaycontainerregistry.azurecr.io/mssql
    container_name: mssql
    ports:
      - '1433:1433'
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
      - SA_PASSWORD=${DB_PASSWORD}
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=root
      - MYSQL_ROOT_HOST=%
    ports:
      - '3306:3306'
    restart: always
