version: '3.4'
services:
  nginx:
    volumes:
      - './nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './nginx/sites-enabled:/etc/nginx/sites-enabled/'
      - './nginx/static:/usr/share/nginx/'
  mssql:
    volumes:
      - 'C:/db/mssql:/var/opt/mssql'
    environment:
      - SA_PASSWORD=P@kistan7861
