apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: qf-api-prod-deployment
spec:
  selector:
    matchLabels:
      app: qf-api-prod
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      name: qf-api-prod
      labels:
        app: qf-api-prod
    spec:
      containers:
        - name: qf-api-prod
          image: bkafarooq/qf.api.prod:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: qf-api-prod-service
spec:
  type: NodePort
  selector:
    app: qf-api-prod
  ports:
    - name: qf-api-prod-port
      port: 80
      protocol: TCP
---
# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   name: qf-portal-prod-ingress
#   annotations:
#     kubernetes.io/ingress.class: nginx
#     nginx.ingress.kubernetes.io/rewrite-target: /
#     kubernetes.io/ingress.class: addon-http-application-routing
#     nginx.ingress.kubernetes.io/rewrite-target: /$1
#     nginx.ingress.kubernetes.io/use-regex: "true"
# spec:
#   rules:
#     - host: prod.quickanalytixqa.nl
#       http:
#         paths:
#           - backend:
#               service:
#                 name: qf-api-prod-service
#                 port:
#                   number: 80
